[versions]
kotlin = "2.0.0"
[libraries]
junit = "junit:junit:4.13.2"
kaml =  "com.charleskorn.kaml:kaml:0.60.0"
kotlin-poet = "com.squareup:kotlinpoet:1.18.1"
swift-poet = "io.outfoxx:swiftpoet:1.6.5"
[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.1.1" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
