name: make_pr
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  make_pr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/gradle-build-action@v2
      - name: Android アプリリポジトリチェックアウト
        uses: actions/checkout@v3
        with:
          repository: tfandkusu/ga913-android
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          path: ga913-android
      - run: ./gradlew run --args make
      - run: git status
        working-directory: ga913-android
